### ISSUE TITLE
[docker-compose] Include `metrics-addr` flags

### ISSUE THREAD

**Issue by DazWilkin** [google/keytransparency#1203]
The docker-compose file implicitly shows the use of `server` and `sequencer` metrics endpoints on port `8081` by the reference in the port mappings and the healthchecks:

```
  server:
    ports:
      - "443:8080" # json & grpc
      - "8081:8081" # metrics
    command:
      - --addr=0.0.0.0:8080
      - --db=test:zaphod@tcp(db:3306)/test
      - --log-url=log-server:8090
      - --map-url=map-server:8090
      - ...
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8081/metrics"]
```

**NB** The reference to `8081:8081` in `ports` and the port's use in the `healthcheck` even though this port is not obviously used by the container.

This is because the binary defaults the flag `metrics-addr` to `8081`.

**Recommend**
Explicitly reference the `metrics-addr` flag in both `server` and `sequencer` (even though the default value) to be more clear as to intent:

```
  server:
    ports:
      - "443:8080" # json & grpc
      - "8081:8081" # metrics
    command:
      - --addr=0.0.0.0:8080
      - --metrics-addr=0.0.0.0:8081
      - --db=test:zaphod@tcp(db:3306)/test
      - --log-url=log-server:8090
      - --map-url=map-server:8090
      - ...
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8081/metrics"]
```
