### ISSUE TITLE
Prometheus config may reference incorrect [service] names

### ISSUE THREAD

**Issue by DazWilkin** [google/keytransparency#1205]
https://github.com/google/keytransparency/blob/master/deploy/prometheus/prometheus.yml

References hostnames `kt-server` and `kt-signer`:
```
...
scrape_configs:
  - job_name: 'kt-server'
    static_configs:
        - targets: ['kt-server:8081']
  - job_name: 'kt-signer'
    static_configs:
        - targets: ['kt-signer:8081']
```
I think these should now be `server` and `sequencer` respectively:
```
...
scrape_configs:
  - job_name: 'server'
    static_configs:
        - targets: ['server:8081']
  - job_name: 'sequencer'
    static_configs:
        - targets: ['sequencer:8081']
```
